/**
 * Static Indonesian Regional Data (RajaOngkir Starter Standard)
 * Provinces 1-34 + Major Cities
 * This data is hardcoded to avoid network connectivity issues
 */

export interface Province {
  province_id: string;
  province: string;
}

export interface City {
  city_id: string;
  city_name: string;
  type: string;
  postal_code: string;
  province_id?: string;
}

export const PROVINCES: Province[] = [
  { province_id: "1", province: "Bali" },
  { province_id: "2", province: "Bangka Belitung" },
  { province_id: "3", province: "Banten" },
  { province_id: "4", province: "Bengkulu" },
  { province_id: "5", province: "DI Yogyakarta" },
  { province_id: "6", province: "DKI Jakarta" },
  { province_id: "7", province: "Gorontalo" },
  { province_id: "8", province: "Jambi" },
  { province_id: "9", province: "Jawa Barat" },
  { province_id: "10", province: "Jawa Tengah" },
  { province_id: "11", province: "Jawa Timur" },
  { province_id: "12", province: "Kalimantan Barat" },
  { province_id: "13", province: "Kalimantan Selatan" },
  { province_id: "14", province: "Kalimantan Tengah" },
  { province_id: "15", province: "Kalimantan Timur" },
  { province_id: "16", province: "Kepulauan Riau" },
  { province_id: "17", province: "Lampung" },
  { province_id: "18", province: "Maluku" },
  { province_id: "19", province: "Maluku Utara" },
  { province_id: "20", province: "Nusa Tenggara Barat" },
  { province_id: "21", province: "Nusa Tenggara Timur" },
  { province_id: "22", province: "Papua" },
  { province_id: "23", province: "Papua Barat" },
  { province_id: "24", province: "Riau" },
  { province_id: "25", province: "Sulawesi Barat" },
  { province_id: "26", province: "Sulawesi Selatan" },
  { province_id: "27", province: "Sulawesi Tengah" },
  { province_id: "28", province: "Sulawesi Tenggara" },
  { province_id: "29", province: "Sulawesi Utara" },
  { province_id: "30", province: "Sumatera Barat" },
  { province_id: "31", province: "Sumatera Selatan" },
  { province_id: "32", province: "Sumatera Utara" },
  { province_id: "33", province: "Aceh" },
  { province_id: "34", province: "Kalimantan Utara" },
];

export const CITIES_BY_PROVINCE: { [provinceId: string]: City[] } = {
  "1": [
    { city_id: "570", city_name: "Kota Denpasar", type: "city", postal_code: "80111" },
    { city_id: "571", city_name: "Kabupaten Badung", type: "regency", postal_code: "80351" },
    { city_id: "572", city_name: "Kabupaten Bangli", type: "regency", postal_code: "80614" },
    { city_id: "573", city_name: "Kabupaten Buleleng", type: "regency", postal_code: "81111" },
    { city_id: "574", city_name: "Kabupaten Gianyar", type: "regency", postal_code: "80511" },
    { city_id: "575", city_name: "Kabupaten Jembrana", type: "regency", postal_code: "82211" },
    { city_id: "576", city_name: "Kabupaten Karangasem", type: "regency", postal_code: "80811" },
    { city_id: "577", city_name: "Kabupaten Klungkung", type: "regency", postal_code: "80711" },
    { city_id: "578", city_name: "Kabupaten Tabanan", type: "regency", postal_code: "82111" },
  ],
  "2": [
    { city_id: "63", city_name: "Kota Pangkal Pinang", type: "city", postal_code: "33141" },
    { city_id: "64", city_name: "Kabupaten Belitung", type: "regency", postal_code: "33411" },
    { city_id: "65", city_name: "Kabupaten Belitung Timur", type: "regency", postal_code: "33913" },
    { city_id: "66", city_name: "Kabupaten Bangka", type: "regency", postal_code: "33712" },
    { city_id: "67", city_name: "Kabupaten Bangka Barat", type: "regency", postal_code: "33812" },
    { city_id: "68", city_name: "Kabupaten Bangka Selatan", type: "regency", postal_code: "33711" },
    { city_id: "69", city_name: "Kabupaten Bangka Tengah", type: "regency", postal_code: "33312" },
  ],
  "3": [
    { city_id: "106", city_name: "Kota Cilegon", type: "city", postal_code: "42411" },
    { city_id: "107", city_name: "Kota Serang", type: "city", postal_code: "42111" },
    { city_id: "108", city_name: "Kota Tangerang", type: "city", postal_code: "15111" },
    { city_id: "109", city_name: "Kota Tangerang Selatan", type: "city", postal_code: "15310" },
    { city_id: "110", city_name: "Kabupaten Pandeglang", type: "regency", postal_code: "42211" },
    { city_id: "111", city_name: "Kabupaten Lebak", type: "regency", postal_code: "42311" },
    { city_id: "112", city_name: "Kabupaten Serang", type: "regency", postal_code: "42161" },
    { city_id: "113", city_name: "Kabupaten Tangerang", type: "regency", postal_code: "15810" },
  ],
  "4": [
    { city_id: "1080", city_name: "Kota Bengkulu", type: "city", postal_code: "38211" },
    { city_id: "1081", city_name: "Kabupaten Kaur", type: "regency", postal_code: "38866" },
    { city_id: "1082", city_name: "Kabupaten Kepahiang", type: "regency", postal_code: "39366" },
    { city_id: "1083", city_name: "Kabupaten Lebong", type: "regency", postal_code: "39367" },
    { city_id: "1084", city_name: "Kabupaten Muko Muko", type: "regency", postal_code: "38461" },
    { city_id: "1085", city_name: "Kabupaten Rejang Lebong", type: "regency", postal_code: "39211" },
    { city_id: "1086", city_name: "Kabupaten Seluma", type: "regency", postal_code: "38811" },
    { city_id: "1087", city_name: "Kabupaten Bengkulu Selatan", type: "regency", postal_code: "38763" },
    { city_id: "1088", city_name: "Kabupaten Bengkulu Utara", type: "regency", postal_code: "38316" },
  ],
  "5": [
    { city_id: "433", city_name: "Kota Yogyakarta", type: "city", postal_code: "55111" },
    { city_id: "434", city_name: "Kabupaten Sleman", type: "regency", postal_code: "55511" },
    { city_id: "435", city_name: "Kabupaten Bantul", type: "regency", postal_code: "55711" },
    { city_id: "436", city_name: "Kabupaten Gunungkidul", type: "regency", postal_code: "55811" },
    { city_id: "437", city_name: "Kabupaten Kulon Progo", type: "regency", postal_code: "55611" },
  ],
  "6": [
    { city_id: "154", city_name: "Kota Jakarta Barat", type: "city", postal_code: "11220" },
    { city_id: "155", city_name: "Kota Jakarta Pusat", type: "city", postal_code: "12110" },
    { city_id: "156", city_name: "Kota Jakarta Selatan", type: "city", postal_code: "12250" },
    { city_id: "157", city_name: "Kota Jakarta Timur", type: "city", postal_code: "13330" },
    { city_id: "158", city_name: "Kota Jakarta Utara", type: "city", postal_code: "14110" },
    { city_id: "159", city_name: "Kabupaten Kepulauan Seribu", type: "regency", postal_code: "14540" },
  ],
  "7": [
    { city_id: "434", city_name: "Kota Gorontalo", type: "city", postal_code: "96111" },
    { city_id: "435", city_name: "Kabupaten Boalemo", type: "regency", postal_code: "96211" },
    { city_id: "436", city_name: "Kabupaten Bone Bolango", type: "regency", postal_code: "96411" },
    { city_id: "437", city_name: "Kabupaten Gorontalo", type: "regency", postal_code: "96515" },
    { city_id: "438", city_name: "Kabupaten Pohuwato", type: "regency", postal_code: "96711" },
  ],
  "8": [
    { city_id: "329", city_name: "Kota Jambi", type: "city", postal_code: "36124" },
    { city_id: "330", city_name: "Kabupaten Kerinci", type: "regency", postal_code: "37211" },
    { city_id: "331", city_name: "Kabupaten Merangin", type: "regency", postal_code: "37311" },
    { city_id: "332", city_name: "Kabupaten Sarolangun", type: "regency", postal_code: "37411" },
    { city_id: "333", city_name: "Kabupaten Batanghari", type: "regency", postal_code: "37221" },
    { city_id: "334", city_name: "Kabupaten Muaro Jambi", type: "regency", postal_code: "36361" },
    { city_id: "335", city_name: "Kabupaten Tanjab Timur", type: "regency", postal_code: "36712" },
    { city_id: "336", city_name: "Kabupaten Tanjab Barat", type: "regency", postal_code: "36411" },
  ],
  "9": [
    { city_id: "71", city_name: "Kota Bandung", type: "city", postal_code: "40111" },
    { city_id: "73", city_name: "Kota Bekasi", type: "city", postal_code: "17121" },
    { city_id: "75", city_name: "Kota Bogor", type: "city", postal_code: "16111" },
    { city_id: "77", city_name: "Kota Cimahi", type: "city", postal_code: "40511" },
    { city_id: "79", city_name: "Kota Depok", type: "city", postal_code: "16421" },
    { city_id: "79", city_name: "Kota Sukabumi", type: "city", postal_code: "43111" },
    { city_id: "80", city_name: "Kota Tasikmalaya", type: "city", postal_code: "46111" },
    { city_id: "81", city_name: "Kabupaten Bandung", type: "regency", postal_code: "40311" },
    { city_id: "82", city_name: "Kabupaten Bandung Barat", type: "regency", postal_code: "40721" },
    { city_id: "83", city_name: "Kabupaten Bekasi", type: "regency", postal_code: "17810" },
    { city_id: "84", city_name: "Kabupaten Bogor", type: "regency", postal_code: "16710" },
    { city_id: "85", city_name: "Kabupaten Ciamis", type: "regency", postal_code: "46211" },
    { city_id: "86", city_name: "Kabupaten Cianjur", type: "regency", postal_code: "43211" },
    { city_id: "87", city_name: "Kabupaten Cirebon", type: "regency", postal_code: "45211" },
    { city_id: "88", city_name: "Kabupaten Garut", type: "regency", postal_code: "44111" },
    { city_id: "89", city_name: "Kabupaten Indramayu", type: "regency", postal_code: "45211" },
    { city_id: "90", city_name: "Kabupaten Karawang", type: "regency", postal_code: "41211" },
    { city_id: "91", city_name: "Kabupaten Kuningan", type: "regency", postal_code: "45311" },
    { city_id: "92", city_name: "Kabupaten Majalengka", type: "regency", postal_code: "45411" },
    { city_id: "93", city_name: "Kabupaten Pangandaran", type: "regency", postal_code: "46811" },
    { city_id: "94", city_name: "Kabupaten Purwakarta", type: "regency", postal_code: "41211" },
    { city_id: "95", city_name: "Kabupaten Subang", type: "regency", postal_code: "41211" },
    { city_id: "96", city_name: "Kabupaten Sukabumi", type: "regency", postal_code: "43211" },
    { city_id: "97", city_name: "Kabupaten Sumedang", type: "regency", postal_code: "45311" },
    { city_id: "98", city_name: "Kabupaten Tasikmalaya", type: "regency", postal_code: "46211" },
  ],
  "10": [
    { city_id: "174", city_name: "Kota Magelang", type: "city", postal_code: "56111" },
    { city_id: "175", city_name: "Kota Pekalongan", type: "city", postal_code: "51111" },
    { city_id: "176", city_name: "Kota Salatiga", type: "city", postal_code: "50711" },
    { city_id: "177", city_name: "Kota Semarang", type: "city", postal_code: "50111" },
    { city_id: "178", city_name: "Kota Surakarta", type: "city", postal_code: "57111" },
    { city_id: "179", city_name: "Kota Tegal", type: "city", postal_code: "34111" },
    { city_id: "180", city_name: "Kabupaten Banjarnegara", type: "regency", postal_code: "53412" },
    { city_id: "181", city_name: "Kabupaten Banyumas", type: "regency", postal_code: "53311" },
    { city_id: "182", city_name: "Kabupaten Batang", type: "regency", postal_code: "51211" },
    { city_id: "183", city_name: "Kabupaten Blora", type: "regency", postal_code: "58211" },
    { city_id: "184", city_name: "Kabupaten Boyolali", type: "regency", postal_code: "57311" },
    { city_id: "185", city_name: "Kabupaten Brebes", type: "regency", postal_code: "52211" },
    { city_id: "186", city_name: "Kabupaten Cilacap", type: "regency", postal_code: "53211" },
    { city_id: "187", city_name: "Kabupaten Demak", type: "regency", postal_code: "59511" },
    { city_id: "188", city_name: "Kabupaten Grobogan", type: "regency", postal_code: "58211" },
    { city_id: "189", city_name: "Kabupaten Jepara", type: "regency", postal_code: "59411" },
    { city_id: "190", city_name: "Kabupaten Karanganyar", type: "regency", postal_code: "57711" },
    { city_id: "191", city_name: "Kabupaten Kebumen", type: "regency", postal_code: "54311" },
    { city_id: "192", city_name: "Kabupaten Kendal", type: "regency", postal_code: "51311" },
    { city_id: "193", city_name: "Kabupaten Klaten", type: "regency", postal_code: "57411" },
    { city_id: "194", city_name: "Kabupaten Kudus", type: "regency", postal_code: "59311" },
    { city_id: "195", city_name: "Kabupaten Magelang", type: "regency", postal_code: "56211" },
    { city_id: "196", city_name: "Kabupaten Muhammadiyah", type: "regency", postal_code: "51211" },
    { city_id: "197", city_name: "Kabupaten Pati", type: "regency", postal_code: "59111" },
    { city_id: "198", city_name: "Kabupaten Pekalongan", type: "regency", postal_code: "51311" },
    { city_id: "199", city_name: "Kabupaten Pemalang", type: "regency", postal_code: "52211" },
    { city_id: "200", city_name: "Kabupaten Purbalingga", type: "regency", postal_code: "53311" },
    { city_id: "201", city_name: "Kabupaten Purworejo", type: "regency", postal_code: "54111" },
    { city_id: "202", city_name: "Kabupaten Rembang", type: "regency", postal_code: "59211" },
    { city_id: "203", city_name: "Kabupaten Semarang", type: "regency", postal_code: "50611" },
    { city_id: "204", city_name: "Kabupaten Sragen", type: "regency", postal_code: "57211" },
    { city_id: "205", city_name: "Kabupaten Sukoharjo", type: "regency", postal_code: "57511" },
    { city_id: "206", city_name: "Kabupaten Sumusi", type: "regency", postal_code: "57611" },
    { city_id: "207", city_name: "Kabupaten Temanggung", type: "regency", postal_code: "56211" },
    { city_id: "208", city_name: "Kabupaten Tegal", type: "regency", postal_code: "52211" },
    { city_id: "209", city_name: "Kabupaten Wonogiri", type: "regency", postal_code: "57611" },
    { city_id: "210", city_name: "Kabupaten Wonosobo", type: "regency", postal_code: "56311" },
  ],
  "11": [
    { city_id: "220", city_name: "Kota Kediri", type: "city", postal_code: "64111" },
    { city_id: "221", city_name: "Kota Madiun", type: "city", postal_code: "63111" },
    { city_id: "222", city_name: "Kota Mojokerto", type: "city", postal_code: "61111" },
    { city_id: "223", city_name: "Kota Pasuruan", type: "city", postal_code: "67111" },
    { city_id: "224", city_name: "Kota Probolinggo", type: "city", postal_code: "67211" },
    { city_id: "225", city_name: "Kota Surabaya", type: "city", postal_code: "60111" },
    { city_id: "226", city_name: "Kabupaten Bangkalan", type: "regency", postal_code: "69211" },
    { city_id: "227", city_name: "Kabupaten Banyuwangi", type: "regency", postal_code: "68411" },
    { city_id: "228", city_name: "Kabupaten Blitar", type: "regency", postal_code: "66211" },
    { city_id: "229", city_name: "Kabupaten Bojonegoro", type: "regency", postal_code: "62111" },
    { city_id: "230", city_name: "Kabupaten Bondowoso", type: "regency", postal_code: "68211" },
    { city_id: "231", city_name: "Kabupaten Gresik", type: "regency", postal_code: "61111" },
    { city_id: "232", city_name: "Kabupaten Jombang", type: "regency", postal_code: "61411" },
    { city_id: "233", city_name: "Kabupaten Kediri", type: "regency", postal_code: "64211" },
    { city_id: "234", city_name: "Kabupaten Lamongan", type: "regency", postal_code: "62211" },
    { city_id: "235", city_name: "Kabupaten Lumajang", type: "regency", postal_code: "67311" },
    { city_id: "236", city_name: "Kabupaten Madiun", type: "regency", postal_code: "63211" },
    { city_id: "237", city_name: "Kabupaten Magetan", type: "regency", postal_code: "63411" },
    { city_id: "238", city_name: "Kabupaten Mojokerto", type: "regency", postal_code: "61211" },
    { city_id: "239", city_name: "Kabupaten Nganjuk", type: "regency", postal_code: "64411" },
    { city_id: "240", city_name: "Kabupaten Ngawi", type: "regency", postal_code: "63811" },
    { city_id: "241", city_name: "Kabupaten Pacitan", type: "regency", postal_code: "63511" },
    { city_id: "242", city_name: "Kabupaten Pamekasan", type: "regency", postal_code: "69311" },
    { city_id: "243", city_name: "Kabupaten Pasuruan", type: "regency", postal_code: "67211" },
    { city_id: "244", city_name: "Kabupaten Ponorogo", type: "regency", postal_code: "63411" },
    { city_id: "245", city_name: "Kabupaten Probolinggo", type: "regency", postal_code: "67311" },
    { city_id: "246", city_name: "Kabupaten Sampang", type: "regency", postal_code: "69411" },
    { city_id: "247", city_name: "Kabupaten Sidoarjo", type: "regency", postal_code: "61211" },
    { city_id: "248", city_name: "Kabupaten Situbondo", type: "regency", postal_code: "68411" },
    { city_id: "249", city_name: "Kabupaten Sumenep", type: "regency", postal_code: "69611" },
    { city_id: "250", city_name: "Kabupaten Trenggalek", type: "regency", postal_code: "66211" },
    { city_id: "251", city_name: "Kabupaten Tuban", type: "regency", postal_code: "62311" },
    { city_id: "252", city_name: "Kabupaten Tulungagung", type: "regency", postal_code: "66211" },
  ],
  "12": [
    { city_id: "381", city_name: "Kota Pontianak", type: "city", postal_code: "78111" },
    { city_id: "382", city_name: "Kota Singkawang", type: "city", postal_code: "79111" },
    { city_id: "383", city_name: "Kabupaten Bengkayang", type: "regency", postal_code: "79211" },
    { city_id: "384", city_name: "Kabupaten Kapuas Hulu", type: "regency", postal_code: "79711" },
    { city_id: "385", city_name: "Kabupaten Kubu Raya", type: "regency", postal_code: "78111" },
    { city_id: "386", city_name: "Kabupaten Landak", type: "regency", postal_code: "78411" },
    { city_id: "387", city_name: "Kabupaten Mempawah", type: "regency", postal_code: "78311" },
    { city_id: "388", city_name: "Kabupaten Sambas", type: "regency", postal_code: "79411" },
    { city_id: "389", city_name: "Kabupaten Sanggau", type: "regency", postal_code: "78611" },
    { city_id: "390", city_name: "Kabupaten Sekadau", type: "regency", postal_code: "78811" },
    { city_id: "391", city_name: "Kabupaten Sintang", type: "regency", postal_code: "78711" },
  ],
  "13": [
    { city_id: "368", city_name: "Kota Banjarmasin", type: "city", postal_code: "70111" },
    { city_id: "369", city_name: "Kota Banjarbaru", type: "city", postal_code: "70711" },
    { city_id: "370", city_name: "Kabupaten Barito Kuala", type: "regency", postal_code: "70811" },
    { city_id: "371", city_name: "Kabupaten Banjar", type: "regency", postal_code: "71211" },
    { city_id: "372", city_name: "Kabupaten Hulu Sungai Selatan", type: "regency", postal_code: "71811" },
    { city_id: "373", city_name: "Kabupaten Hulu Sungai Tengah", type: "regency", postal_code: "71511" },
    { city_id: "374", city_name: "Kabupaten Hulu Sungai Utara", type: "regency", postal_code: "71411" },
    { city_id: "375", city_name: "Kabupaten Kotabaru", type: "regency", postal_code: "72211" },
    { city_id: "376", city_name: "Kabupaten Kubu Raya", type: "regency", postal_code: "72311" },
    { city_id: "377", city_name: "Kabupaten Murung Raya", type: "regency", postal_code: "73611" },
    { city_id: "378", city_name: "Kabupaten Tabalong", type: "regency", postal_code: "72311" },
    { city_id: "379", city_name: "Kabupaten Tanah Bumbu", type: "regency", postal_code: "72211" },
    { city_id: "380", city_name: "Kabupaten Tana Tidung", type: "regency", postal_code: "72611" },
  ],
  "14": [
    { city_id: "336", city_name: "Kota Palangka Raya", type: "city", postal_code: "73111" },
    { city_id: "337", city_name: "Kabupaten Barito Selatan", type: "regency", postal_code: "73501" },
    { city_id: "338", city_name: "Kabupaten Barito Timur", type: "regency", postal_code: "73701" },
    { city_id: "339", city_name: "Kabupaten Barito Utara", type: "regency", postal_code: "73711" },
    { city_id: "340", city_name: "Kabupaten Gunung Mas", type: "regency", postal_code: "74411" },
    { city_id: "341", city_name: "Kabupaten Kapuas", type: "regency", postal_code: "73111" },
    { city_id: "342", city_name: "Kabupaten Katingan", type: "regency", postal_code: "73611" },
    { city_id: "343", city_name: "Kabupaten Kotawaringin Barat", type: "regency", postal_code: "73811" },
    { city_id: "344", city_name: "Kabupaten Kotawaringin Timur", type: "regency", postal_code: "73911" },
    { city_id: "345", city_name: "Kabupaten Lamandau", type: "regency", postal_code: "74111" },
    { city_id: "346", city_name: "Kabupaten Murung Raya", type: "regency", postal_code: "74211" },
    { city_id: "347", city_name: "Kabupaten Pulang Pisau", type: "regency", postal_code: "73411" },
    { city_id: "348", city_name: "Kabupaten Sukamara", type: "regency", postal_code: "74211" },
    { city_id: "349", city_name: "Kabupaten Seruyan", type: "regency", postal_code: "74411" },
  ],
  "15": [
    { city_id: "355", city_name: "Kota Balikpapan", type: "city", postal_code: "76111" },
    { city_id: "356", city_name: "Kota Bontang", type: "city", postal_code: "75313" },
    { city_id: "357", city_name: "Kota Samarinda", type: "city", postal_code: "75111" },
    { city_id: "358", city_name: "Kota Tarakan", type: "city", postal_code: "77111" },
    { city_id: "359", city_name: "Kabupaten Berau", type: "regency", postal_code: "77212" },
    { city_id: "360", city_name: "Kabupaten Kutai Barat", type: "regency", postal_code: "75512" },
    { city_id: "361", city_name: "Kabupaten Kutai Kartanegara", type: "regency", postal_code: "75411" },
    { city_id: "362", city_name: "Kabupaten Kutai Timur", type: "regency", postal_code: "75612" },
    { city_id: "363", city_name: "Kabupaten Pasir", type: "regency", postal_code: "76211" },
    { city_id: "364", city_name: "Kabupaten Penajam Paser Utara", type: "regency", postal_code: "76211" },
    { city_id: "365", city_name: "Kabupaten Paser", type: "regency", postal_code: "76211" },
  ],
  "16": [
    { city_id: "527", city_name: "Kota Batam", type: "city", postal_code: "29421" },
    { city_id: "528", city_name: "Kota Tanjungpinang", type: "city", postal_code: "29111" },
    { city_id: "529", city_name: "Kabupaten Bintan", type: "regency", postal_code: "29152" },
    { city_id: "530", city_name: "Kabupaten Karimun", type: "regency", postal_code: "29651" },
    { city_id: "531", city_name: "Kabupaten Kepulauan Anambas", type: "regency", postal_code: "29852" },
    { city_id: "532", city_name: "Kabupaten Lingga", type: "regency", postal_code: "29811" },
    { city_id: "533", city_name: "Kabupaten Natuna", type: "regency", postal_code: "29752" },
  ],
  "17": [
    { city_id: "127", city_name: "Kota Bandar Lampung", type: "city", postal_code: "35111" },
    { city_id: "128", city_name: "Kota Metro", type: "city", postal_code: "34111" },
    { city_id: "129", city_name: "Kabupaten Lampung Barat", type: "regency", postal_code: "34811" },
    { city_id: "130", city_name: "Kabupaten Lampung Selatan", type: "regency", postal_code: "35311" },
    { city_id: "131", city_name: "Kabupaten Lampung Tengah", type: "regency", postal_code: "34611" },
    { city_id: "132", city_name: "Kabupaten Lampung Timur", type: "regency", postal_code: "34411" },
    { city_id: "133", city_name: "Kabupaten Lampung Utara", type: "regency", postal_code: "34711" },
    { city_id: "134", city_name: "Kabupaten Mesuji", type: "regency", postal_code: "35812" },
    { city_id: "135", city_name: "Kabupaten Pesawaran", type: "regency", postal_code: "35511" },
    { city_id: "136", city_name: "Kabupaten Pringsewu", type: "regency", postal_code: "35712" },
    { city_id: "137", city_name: "Kabupaten Tanggamus", type: "regency", postal_code: "35211" },
    { city_id: "138", city_name: "Kabupaten Tulang Bawang", type: "regency", postal_code: "34911" },
    { city_id: "139", city_name: "Kabupaten Tulang Bawang Barat", type: "regency", postal_code: "34912" },
    { city_id: "140", city_name: "Kabupaten Way Kanan", type: "regency", postal_code: "35611" },
  ],
  "18": [
    { city_id: "502", city_name: "Kota Ambon", type: "city", postal_code: "97111" },
    { city_id: "503", city_name: "Kabupaten Buru", type: "regency", postal_code: "97711" },
    { city_id: "504", city_name: "Kabupaten Buru Selatan", type: "regency", postal_code: "97812" },
    { city_id: "505", city_name: "Kabupaten Maluku Barat Daya", type: "regency", postal_code: "97611" },
    { city_id: "506", city_name: "Kabupaten Maluku Tenggara", type: "regency", postal_code: "97411" },
    { city_id: "507", city_name: "Kabupaten Maluku Tenggara Barat", type: "regency", postal_code: "97512" },
    { city_id: "508", city_name: "Kabupaten Seram Bagian Barat", type: "regency", postal_code: "97811" },
    { city_id: "509", city_name: "Kabupaten Seram Bagian Timur", type: "regency", postal_code: "97911" },
  ],
  "19": [
    { city_id: "515", city_name: "Kota Ternate", type: "city", postal_code: "97711" },
    { city_id: "516", city_name: "Kota Tidore Kepulauan", type: "city", postal_code: "97811" },
    { city_id: "517", city_name: "Kabupaten Halmahera Barat", type: "regency", postal_code: "97611" },
    { city_id: "518", city_name: "Kabupaten Halmahera Selatan", type: "regency", postal_code: "97712" },
    { city_id: "519", city_name: "Kabupaten Halmahera Tengah", type: "regency", postal_code: "97712" },
    { city_id: "520", city_name: "Kabupaten Halmahera Timur", type: "regency", postal_code: "97811" },
    { city_id: "521", city_name: "Kabupaten Halmahera Utara", type: "regency", postal_code: "97412" },
    { city_id: "522", city_name: "Kabupaten Kepulauan Sula", type: "regency", postal_code: "97511" },
    { city_id: "523", city_name: "Kabupaten Morotai", type: "regency", postal_code: "97711" },
    { city_id: "524", city_name: "Kabupaten Pulau Morotai", type: "regency", postal_code: "97871" },
  ],
  "20": [
    { city_id: "556", city_name: "Kota Mataram", type: "city", postal_code: "83111" },
    { city_id: "557", city_name: "Kabupaten Bima", type: "regency", postal_code: "84711" },
    { city_id: "558", city_name: "Kabupaten Dompu", type: "regency", postal_code: "84211" },
    { city_id: "559", city_name: "Kabupaten Lombok Barat", type: "regency", postal_code: "83311" },
    { city_id: "560", city_name: "Kabupaten Lombok Tengah", type: "regency", postal_code: "83511" },
    { city_id: "561", city_name: "Kabupaten Lombok Timur", type: "regency", postal_code: "83611" },
    { city_id: "562", city_name: "Kabupaten Lombok Utara", type: "regency", postal_code: "83711" },
    { city_id: "563", city_name: "Kota Bima", type: "city", postal_code: "84711" },
  ],
  "21": [
    { city_id: "580", city_name: "Kota Kupang", type: "city", postal_code: "85111" },
    { city_id: "581", city_name: "Kabupaten Alor", type: "regency", postal_code: "85811" },
    { city_id: "582", city_name: "Kabupaten Bangli", type: "regency", postal_code: "86211" },
    { city_id: "583", city_name: "Kabupaten Belu", type: "regency", postal_code: "86111" },
    { city_id: "584", city_name: "Kabupaten Ende", type: "regency", postal_code: "86311" },
    { city_id: "585", city_name: "Kabupaten Flores Timur", type: "regency", postal_code: "86511" },
    { city_id: "586", city_name: "Kabupaten Kupang", type: "regency", postal_code: "85711" },
    { city_id: "587", city_name: "Kabupaten Lembata", type: "regency", postal_code: "86411" },
    { city_id: "588", city_name: "Kabupaten Malaka", type: "regency", postal_code: "85911" },
    { city_id: "589", city_name: "Kabupaten Manggarai", type: "regency", postal_code: "86611" },
    { city_id: "590", city_name: "Kabupaten Manggarai Barat", type: "regency", postal_code: "86811" },
    { city_id: "591", city_name: "Kabupaten Manggarai Timur", type: "regency", postal_code: "86711" },
    { city_id: "592", city_name: "Kabupaten Ngada", type: "regency", postal_code: "86411" },
    { city_id: "593", city_name: "Kabupaten Rote Ndao", type: "regency", postal_code: "85911" },
    { city_id: "594", city_name: "Kabupaten Sabu Raijua", type: "regency", postal_code: "85911" },
    { city_id: "595", city_name: "Kabupaten Sikka", type: "regency", postal_code: "86411" },
    { city_id: "596", city_name: "Kabupaten Timor Tengah Selatan", type: "regency", postal_code: "85511" },
    { city_id: "597", city_name: "Kabupaten Timor Tengah Utara", type: "regency", postal_code: "85411" },
  ],
  "22": [
    { city_id: "638", city_name: "Kota Jayapura", type: "city", postal_code: "99111" },
    { city_id: "639", city_name: "Kabupaten Asmat", type: "regency", postal_code: "99711" },
    { city_id: "640", city_name: "Kabupaten Biak Numfor", type: "regency", postal_code: "98111" },
    { city_id: "641", city_name: "Kabupaten Boven Digoel", type: "regency", postal_code: "99511" },
    { city_id: "642", city_name: "Kabupaten Deiyai", type: "regency", postal_code: "99611" },
    { city_id: "643", city_name: "Kabupaten Dogiyai", type: "regency", postal_code: "99711" },
    { city_id: "644", city_name: "Kabupaten Intan Jaya", type: "regency", postal_code: "99811" },
    { city_id: "645", city_name: "Kabupaten Jayapura", type: "regency", postal_code: "99211" },
    { city_id: "646", city_name: "Kabupaten Jayawijaya", type: "regency", postal_code: "99311" },
    { city_id: "647", city_name: "Kabupaten Kerom", type: "regency", postal_code: "99411" },
    { city_id: "648", city_name: "Kabupaten Keerom", type: "regency", postal_code: "99411" },
    { city_id: "649", city_name: "Kabupaten Lanny Jaya", type: "regency", postal_code: "99511" },
    { city_id: "650", city_name: "Kabupaten Mamberamo Raya", type: "regency", postal_code: "99511" },
    { city_id: "651", city_name: "Kabupaten Mamberamo Tengah", type: "regency", postal_code: "99611" },
    { city_id: "652", city_name: "Kabupaten Mappi", type: "regency", postal_code: "99811" },
    { city_id: "653", city_name: "Kabupaten Merauke", type: "regency", postal_code: "99611" },
    { city_id: "654", city_name: "Kabupaten Mimika", type: "regency", postal_code: "99711" },
    { city_id: "655", city_name: "Kabupaten Nabire", type: "regency", postal_code: "98811" },
    { city_id: "656", city_name: "Kabupaten Nduga", type: "regency", postal_code: "99411" },
    { city_id: "657", city_name: "Kabupaten Paniai", type: "regency", postal_code: "99711" },
    { city_id: "658", city_name: "Kabupaten Pegunungan Bintang", type: "regency", postal_code: "99511" },
    { city_id: "659", city_name: "Kabupaten Puncak", type: "regency", postal_code: "99611" },
    { city_id: "660", city_name: "Kabupaten Puncak Jaya", type: "regency", postal_code: "99711" },
    { city_id: "661", city_name: "Kabupaten Sarmi", type: "regency", postal_code: "99411" },
    { city_id: "662", city_name: "Kabupaten Supiori", type: "regency", postal_code: "98211" },
    { city_id: "663", city_name: "Kabupaten Tolikara", type: "regency", postal_code: "99711" },
    { city_id: "664", city_name: "Kabupaten Waropen", type: "regency", postal_code: "99911" },
    { city_id: "665", city_name: "Kabupaten Yahukimo", type: "regency", postal_code: "99811" },
    { city_id: "666", city_name: "Kabupaten Yalimo", type: "regency", postal_code: "99811" },
  ],
  "23": [
    { city_id: "612", city_name: "Kota Sorong", type: "city", postal_code: "98411" },
    { city_id: "613", city_name: "Kabupaten Bombana", type: "regency", postal_code: "98811" },
    { city_id: "614", city_name: "Kabupaten Fakfak", type: "regency", postal_code: "98611" },
    { city_id: "615", city_name: "Kabupaten Kaimana", type: "regency", postal_code: "98711" },
    { city_id: "616", city_name: "Kabupaten Manokwari", type: "regency", postal_code: "98311" },
    { city_id: "617", city_name: "Kabupaten Manokwari Selatan", type: "regency", postal_code: "98312" },
    { city_id: "618", city_name: "Kabupaten Maybrat", type: "regency", postal_code: "98411" },
    { city_id: "619", city_name: "Kabupaten Pegunungan Arfak", type: "regency", postal_code: "98211" },
    { city_id: "620", city_name: "Kabupaten Raja Ampat", type: "regency", postal_code: "98281" },
    { city_id: "621", city_name: "Kabupaten Sorong", type: "regency", postal_code: "98511" },
    { city_id: "622", city_name: "Kabupaten Tambrauw", type: "regency", postal_code: "98511" },
    { city_id: "623", city_name: "Kabupaten Teluk Bintuni", type: "regency", postal_code: "98511" },
    { city_id: "624", city_name: "Kabupaten Teluk Wondama", type: "regency", postal_code: "98511" },
    { city_id: "625", city_name: "Kota Manado", type: "city", postal_code: "95111" },
  ],
  "24": [
    { city_id: "286", city_name: "Kota Pekanbaru", type: "city", postal_code: "28111" },
    { city_id: "287", city_name: "Kota Dumai", type: "city", postal_code: "28811" },
    { city_id: "288", city_name: "Kabupaten Bengkalis", type: "regency", postal_code: "28711" },
    { city_id: "289", city_name: "Kabupaten Indragiri Hilir", type: "regency", postal_code: "29211" },
    { city_id: "290", city_name: "Kabupaten Indragiri Hulu", type: "regency", postal_code: "29311" },
    { city_id: "291", city_name: "Kabupaten Kampar", type: "regency", postal_code: "28611" },
    { city_id: "292", city_name: "Kabupaten Kuantan Singingi", type: "regency", postal_code: "28711" },
    { city_id: "293", city_name: "Kabupaten Pelalawan", type: "regency", postal_code: "28511" },
    { city_id: "294", city_name: "Kabupaten Rokan Hilir", type: "regency", postal_code: "28811" },
    { city_id: "295", city_name: "Kabupaten Rokan Hulu", type: "regency", postal_code: "28711" },
    { city_id: "296", city_name: "Kabupaten Siak", type: "regency", postal_code: "28611" },
  ],
  "25": [
    { city_id: "445", city_name: "Kota Mamuju", type: "city", postal_code: "90411" },
    { city_id: "446", city_name: "Kabupaten Mamasa", type: "regency", postal_code: "90511" },
    { city_id: "447", city_name: "Kabupaten Mamuju", type: "regency", postal_code: "90511" },
    { city_id: "448", city_name: "Kabupaten Mamuju Utara", type: "regency", postal_code: "91511" },
    { city_id: "449", city_name: "Kabupaten Poliwali Mandar", type: "regency", postal_code: "90611" },
  ],
  "26": [
    { city_id: "418", city_name: "Kota Makassar", type: "city", postal_code: "90111" },
    { city_id: "419", city_name: "Kota Palopo", type: "city", postal_code: "91911" },
    { city_id: "420", city_name: "Kota Parepare", type: "city", postal_code: "91111" },
    { city_id: "421", city_name: "Kabupaten Bantaeng", type: "regency", postal_code: "90511" },
    { city_id: "422", city_name: "Kabupaten Barru", type: "regency", postal_code: "90711" },
    { city_id: "423", city_name: "Kabupaten Bone", type: "regency", postal_code: "92711" },
    { city_id: "424", city_name: "Kabupaten Bulukumba", type: "regency", postal_code: "90511" },
    { city_id: "425", city_name: "Kabupaten Enrekang", type: "regency", postal_code: "91811" },
    { city_id: "426", city_name: "Kabupaten Gowa", type: "regency", postal_code: "92211" },
    { city_id: "427", city_name: "Kabupaten Jeneponto", type: "regency", postal_code: "90611" },
    { city_id: "428", city_name: "Kabupaten Kepulauan Selayar", type: "regency", postal_code: "90711" },
    { city_id: "429", city_name: "Kabupaten Luwu", type: "regency", postal_code: "91511" },
    { city_id: "430", city_name: "Kabupaten Luwu Timur", type: "regency", postal_code: "91611" },
    { city_id: "431", city_name: "Kabupaten Luwu Utara", type: "regency", postal_code: "91711" },
    { city_id: "432", city_name: "Kabupaten Maros", type: "regency", postal_code: "90511" },
    { city_id: "433", city_name: "Kabupaten Pangkajene Kepulauan", type: "regency", postal_code: "90811" },
    { city_id: "434", city_name: "Kabupaten Pinrang", type: "regency", postal_code: "91311" },
    { city_id: "435", city_name: "Kabupaten Sidenreng Rappang", type: "regency", postal_code: "91411" },
    { city_id: "436", city_name: "Kabupaten Sinjai", type: "regency", postal_code: "92611" },
    { city_id: "437", city_name: "Kabupaten Soppeng", type: "regency", postal_code: "90811" },
    { city_id: "438", city_name: "Kabupaten Takalar", type: "regency", postal_code: "90711" },
    { city_id: "439", city_name: "Kabupaten Tana Toraja", type: "regency", postal_code: "91811" },
    { city_id: "440", city_name: "Kabupaten Toraja Utara", type: "regency", postal_code: "91911" },
    { city_id: "441", city_name: "Kabupaten Wajo", type: "regency", postal_code: "90811" },
  ],
  "27": [
    { city_id: "399", city_name: "Kota Palu", type: "city", postal_code: "94111" },
    { city_id: "400", city_name: "Kabupaten Banggai", type: "regency", postal_code: "94711" },
    { city_id: "401", city_name: "Kabupaten Banggai Laut", type: "regency", postal_code: "94811" },
    { city_id: "402", city_name: "Kabupaten Banggai Kepulauan", type: "regency", postal_code: "94911" },
    { city_id: "403", city_name: "Kabupaten Buol", type: "regency", postal_code: "94711" },
    { city_id: "404", city_name: "Kabupaten Donggala", type: "regency", postal_code: "94311" },
    { city_id: "405", city_name: "Kabupaten Morowali", type: "regency", postal_code: "94611" },
    { city_id: "406", city_name: "Kabupaten Morowali Utara", type: "regency", postal_code: "94612" },
    { city_id: "407", city_name: "Kabupaten Parigi Moutong", type: "regency", postal_code: "94411" },
    { city_id: "408", city_name: "Kabupaten Poso", type: "regency", postal_code: "94511" },
    { city_id: "409", city_name: "Kabupaten Sigi", type: "regency", postal_code: "94211" },
    { city_id: "410", city_name: "Kabupaten Tojo Una-Una", type: "regency", postal_code: "94711" },
    { city_id: "411", city_name: "Kabupaten Toli-Toli", type: "regency", postal_code: "94711" },
  ],
  "28": [
    { city_id: "381", city_name: "Kota Kendari", type: "city", postal_code: "93111" },
    { city_id: "382", city_name: "Kota Baubau", type: "city", postal_code: "93711" },
    { city_id: "383", city_name: "Kabupaten Bombana", type: "regency", postal_code: "93811" },
    { city_id: "384", city_name: "Kabupaten Buton", type: "regency", postal_code: "93711" },
    { city_id: "385", city_name: "Kabupaten Buton Selatan", type: "regency", postal_code: "93712" },
    { city_id: "386", city_name: "Kabupaten Buton Utara", type: "regency", postal_code: "93713" },
    { city_id: "387", city_name: "Kabupaten Kolaka", type: "regency", postal_code: "93511" },
    { city_id: "388", city_name: "Kabupaten Kolaka Timur", type: "regency", postal_code: "93512" },
    { city_id: "389", city_name: "Kabupaten Konawe", type: "regency", postal_code: "93211" },
    { city_id: "390", city_name: "Kabupaten Konawe Kepulauan", type: "regency", postal_code: "93312" },
    { city_id: "391", city_name: "Kabupaten Konawe Selatan", type: "regency", postal_code: "93412" },
    { city_id: "392", city_name: "Kabupaten Konawe Utara", type: "regency", postal_code: "93312" },
    { city_id: "393", city_name: "Kabupaten Muna", type: "regency", postal_code: "93611" },
    { city_id: "394", city_name: "Kabupaten Muna Barat", type: "regency", postal_code: "93612" },
    { city_id: "395", city_name: "Kabupaten Wakatobi", type: "regency", postal_code: "93791" },
  ],
  "29": [
    { city_id: "353", city_name: "Kota Manado", type: "city", postal_code: "95111" },
    { city_id: "354", city_name: "Kota Tomohon", type: "city", postal_code: "95311" },
    { city_id: "355", city_name: "Kota Bitung", type: "city", postal_code: "95211" },
    { city_id: "356", city_name: "Kabupaten Bolaang Mongondow", type: "regency", postal_code: "95711" },
    { city_id: "357", city_name: "Kabupaten Bolaang Mongondow Selatan", type: "regency", postal_code: "95712" },
    { city_id: "358", city_name: "Kabupaten Bolaang Mongondow Timur", type: "regency", postal_code: "95713" },
    { city_id: "359", city_name: "Kabupaten Bolaang Mongondow Utara", type: "regency", postal_code: "95714" },
    { city_id: "360", city_name: "Kabupaten Kepulauan Sangihe", type: "regency", postal_code: "95711" },
    { city_id: "361", city_name: "Kabupaten Kepulauan Talaud", type: "regency", postal_code: "95811" },
    { city_id: "362", city_name: "Kabupaten Minahasa", type: "regency", postal_code: "95511" },
    { city_id: "363", city_name: "Kabupaten Minahasa Selatan", type: "regency", postal_code: "95512" },
    { city_id: "364", city_name: "Kabupaten Minahasa Tenggara", type: "regency", postal_code: "95513" },
    { city_id: "365", city_name: "Kabupaten Minahasa Utara", type: "regency", postal_code: "95514" },
  ],
  "30": [
    { city_id: "263", city_name: "Kota Padang", type: "city", postal_code: "25111" },
    { city_id: "264", city_name: "Kota Bukittinggi", type: "city", postal_code: "26111" },
    { city_id: "265", city_name: "Kota Payakumbuh", type: "city", postal_code: "26211" },
    { city_id: "266", city_name: "Kota Pariaman", type: "city", postal_code: "25511" },
    { city_id: "267", city_name: "Kabupaten Agam", type: "regency", postal_code: "26411" },
    { city_id: "268", city_name: "Kabupaten Lima Puluh Kota", type: "regency", postal_code: "26311" },
    { city_id: "269", city_name: "Kabupaten Padang Pariaman", type: "regency", postal_code: "25611" },
    { city_id: "270", city_name: "Kabupaten Pasaman", type: "regency", postal_code: "26611" },
    { city_id: "271", city_name: "Kabupaten Pasaman Barat", type: "regency", postal_code: "26711" },
    { city_id: "272", city_name: "Kabupaten Pesisir Selatan", type: "regency", postal_code: "25811" },
    { city_id: "273", city_name: "Kabupaten Solok", type: "regency", postal_code: "27711" },
    { city_id: "274", city_name: "Kabupaten Solok Selatan", type: "regency", postal_code: "27712" },
    { city_id: "275", city_name: "Kabupaten Tanah Datar", type: "regency", postal_code: "27211" },
  ],
  "31": [
    { city_id: "138", city_name: "Kota Palembang", type: "city", postal_code: "30111" },
    { city_id: "139", city_name: "Kota Prabumulih", type: "city", postal_code: "31111" },
    { city_id: "140", city_name: "Kota Lubuklinggau", type: "city", postal_code: "31811" },
    { city_id: "141", city_name: "Kabupaten Banyuasin", type: "regency", postal_code: "30711" },
    { city_id: "142", city_name: "Kabupaten Empat Lawang", type: "regency", postal_code: "31611" },
    { city_id: "143", city_name: "Kabupaten Lahat", type: "regency", postal_code: "31511" },
    { city_id: "144", city_name: "Kabupaten Musi Banyuasin", type: "regency", postal_code: "30811" },
    { city_id: "145", city_name: "Kabupaten Musi Rawas", type: "regency", postal_code: "31311" },
    { city_id: "146", city_name: "Kabupaten Musi Rawas Utara", type: "regency", postal_code: "31312" },
    { city_id: "147", city_name: "Kabupaten Ogan Ilir", type: "regency", postal_code: "30711" },
    { city_id: "148", city_name: "Kabupaten Ogan Komering Ilir", type: "regency", postal_code: "30811" },
    { city_id: "149", city_name: "Kabupaten Ogan Komering Ulu", type: "regency", postal_code: "31311" },
    { city_id: "150", city_name: "Kabupaten Ogan Komering Ulu Selatan", type: "regency", postal_code: "31312" },
    { city_id: "151", city_name: "Kabupaten Ogan Komering Ulu Timur", type: "regency", postal_code: "31313" },
    { city_id: "152", city_name: "Kabupaten Seluma", type: "regency", postal_code: "30611" },
  ],
  "32": [
    { city_id: "1", city_name: "Kota Medan", type: "city", postal_code: "20111" },
    { city_id: "2", city_name: "Kota Binjai", type: "city", postal_code: "20711" },
    { city_id: "3", city_name: "Kota Pematangsiantar", type: "city", postal_code: "21111" },
    { city_id: "4", city_name: "Kota Sibolga", type: "city", postal_code: "22711" },
    { city_id: "5", city_name: "Kota Tanjungbalai", type: "city", postal_code: "21311" },
    { city_id: "6", city_name: "Kota Tebing Tinggi", type: "city", postal_code: "20611" },
    { city_id: "7", city_name: "Kabupaten Asahan", type: "regency", postal_code: "21211" },
    { city_id: "8", city_name: "Kabupaten Batubara", type: "regency", postal_code: "21811" },
    { city_id: "9", city_name: "Kabupaten Batu Bara", type: "regency", postal_code: "21812" },
    { city_id: "10", city_name: "Kabupaten Dairi", type: "regency", postal_code: "22111" },
    { city_id: "11", city_name: "Kabupaten Deli Serdang", type: "regency", postal_code: "20911" },
    { city_id: "12", city_name: "Kabupaten Humbang Hasundutan", type: "regency", postal_code: "22411" },
    { city_id: "13", city_name: "Kabupaten Langkat", type: "regency", postal_code: "20811" },
    { city_id: "14", city_name: "Kabupaten Mandailing Natal", type: "regency", postal_code: "22811" },
    { city_id: "15", city_name: "Kabupaten Nias", type: "regency", postal_code: "22811" },
    { city_id: "16", city_name: "Kabupaten Nias Barat", type: "regency", postal_code: "22912" },
    { city_id: "17", city_name: "Kabupaten Nias Selatan", type: "regency", postal_code: "23111" },
    { city_id: "18", city_name: "Kabupaten Nias Utara", type: "regency", postal_code: "23211" },
    { city_id: "19", city_name: "Kabupaten Padang Lawas", type: "regency", postal_code: "22711" },
    { city_id: "20", city_name: "Kabupaten Padang Lawas Utara", type: "regency", postal_code: "22712" },
    { city_id: "21", city_name: "Kabupaten Pakpak Bharat", type: "regency", postal_code: "22511" },
    { city_id: "22", city_name: "Kabupaten Samosir", type: "regency", postal_code: "22311" },
    { city_id: "23", city_name: "Kabupaten Serdang Bedagai", type: "regency", postal_code: "21011" },
    { city_id: "24", city_name: "Kabupaten Simalungun", type: "regency", postal_code: "21211" },
    { city_id: "25", city_name: "Kabupaten Tapanuli Selatan", type: "regency", postal_code: "22911" },
    { city_id: "26", city_name: "Kabupaten Tapanuli Tengah", type: "regency", postal_code: "23011" },
    { city_id: "27", city_name: "Kabupaten Tapanuli Utara", type: "regency", postal_code: "23111" },
    { city_id: "28", city_name: "Kabupaten Toba Samosir", type: "regency", postal_code: "22411" },
    { city_id: "29", city_name: "Kabupaten Toba", type: "regency", postal_code: "22412" },
  ],
  "33": [
    { city_id: "1", city_name: "Kota Banda Aceh", type: "city", postal_code: "23111" },
    { city_id: "2", city_name: "Kota Langsa", type: "city", postal_code: "24411" },
    { city_id: "3", city_name: "Kota Lhokseumawe", type: "city", postal_code: "24311" },
    { city_id: "4", city_name: "Kota Sabang", type: "city", postal_code: "24211" },
    { city_id: "5", city_name: "Kabupaten Aceh Barat", type: "regency", postal_code: "23611" },
    { city_id: "6", city_name: "Kabupaten Aceh Barat Daya", type: "regency", postal_code: "23712" },
    { city_id: "7", city_name: "Kabupaten Aceh Besar", type: "regency", postal_code: "23311" },
    { city_id: "8", city_name: "Kabupaten Aceh Jaya", type: "regency", postal_code: "23561" },
    { city_id: "9", city_name: "Kabupaten Aceh Selatan", type: "regency", postal_code: "24711" },
    { city_id: "10", city_name: "Kabupaten Aceh Singkil", type: "regency", postal_code: "24811" },
    { city_id: "11", city_name: "Kabupaten Aceh Tamiang", type: "regency", postal_code: "24611" },
    { city_id: "12", city_name: "Kabupaten Aceh Tengah", type: "regency", postal_code: "24511" },
    { city_id: "13", city_name: "Kabupaten Aceh Tenggara", type: "regency", postal_code: "24311" },
    { city_id: "14", city_name: "Kabupaten Aceh Timur", type: "regency", postal_code: "24411" },
    { city_id: "15", city_name: "Kabupaten Aceh Utara", type: "regency", postal_code: "24211" },
    { city_id: "16", city_name: "Kabupaten Bireuen", type: "regency", postal_code: "24211" },
    { city_id: "17", city_name: "Kabupaten Gayo Lues", type: "regency", postal_code: "24611" },
    { city_id: "18", city_name: "Kabupaten Nagan Raya", type: "regency", postal_code: "23811" },
    { city_id: "19", city_name: "Kabupaten Pidie", type: "regency", postal_code: "24111" },
    { city_id: "20", city_name: "Kabupaten Pidie Jaya", type: "regency", postal_code: "24112" },
    { city_id: "21", city_name: "Kabupaten Simeulue", type: "regency", postal_code: "23911" },
  ],
  "34": [
    { city_id: "1", city_name: "Kota Tarakan", type: "city", postal_code: "77111" },
    { city_id: "2", city_name: "Kabupaten Berau", type: "regency", postal_code: "77212" },
    { city_id: "3", city_name: "Kabupaten Bulungan", type: "regency", postal_code: "77311" },
    { city_id: "4", city_name: "Kabupaten Malinau", type: "regency", postal_code: "77411" },
    { city_id: "5", city_name: "Kabupaten Nunukan", type: "regency", postal_code: "77511" },
  ],
};

/**
 * Get all provinces
 */
export function getProvinces(): Province[] {
  return PROVINCES;
}

/**
 * Get cities by province ID
 */
export function getCities(provinceId: string): City[] {
  return CITIES_BY_PROVINCE[provinceId] || [];
}

/**
 * Get a specific province
 */
export function getProvinceById(id: string): Province | undefined {
  return PROVINCES.find(p => p.province_id === id);
}

/**
 * Get a specific city
 */
export function getCityById(provinceId: string, cityId: string): City | undefined {
  const cities = CITIES_BY_PROVINCE[provinceId] || [];
  return cities.find(c => c.city_id === cityId);
}